# helm

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} # place holders
spec:
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}